### ISSUE TITLE
Sparse points are not considered one track

### ISSUE THREAD

**Issue by Cyberes** [Freika/dawarich#231]
**Describe the bug**
I import data from Home Assistant and noticed that Dawarich is getting confused by the long interval between points.

**Version**
 0.13.0

First, here is the track that HA is recording. This shows my movement over the span of 24 hours. Points are about 15 to 20 minutes apart. The HA app records movement 24 hours a day.

![ha](https://github.com/user-attachments/assets/d1d34f9f-034f-4d3e-9238-7780c018cbae)

And here is how Dawarich is interpreting these points:

![dw](https://github.com/user-attachments/assets/a91f5bc1-7198-4343-86de-a6392f3a2889)

I suppose the issue is that Dawarich is assuming that the interval between track points is less than a minute. I suggest accounting for 24-hour recording with a configurable interval between points.

**Comment by chenrik** [comment]
@Cyberes 
You can set the maximum amount of time between points for them to be considered part of the same track. There is a menu for this right under the zoom controls on the map.
![image](https://github.com/user-attachments/assets/93dc48e0-f0b3-42a0-bfe1-4b91306ce914)

**Comment by Cyberes** [comment]
Thanks.

I sent `Minutes between routes` to `30` but the points on the map were not connected. I then tried both `1` and `300` but neither made the sparse points connect.

**Comment by chenrik** [comment]
@Cyberes 

You might have done this already, but you need to reload the map after updating the setting, just press search or reload the page.
It should probably be a feature that the map auto reload on setting changes.

**Comment by Freika** [comment]
@Cyberes Dawarich operates with points rather than tracks. The tracks you see on the map are being calculated and rendered at the page loading, based on the time and distance between points. If points in your imported track are too far away from each other in time and/or distance, they will not be rendered as a track, unless you find a proper combination of settings described above.

In the future there might be operation on tracks level in addition to points level.
