### ISSUE TITLE
Can't import from owntracks as described by docs

### ISSUE THREAD

**Issue by rhyst** [Freika/dawarich#276]
**Describe the bug**

The import page describes using a download button to get data from owntracks however that has been removed: https://github.com/owntracks/frontend/commit/8df1f86ab9257d1acd87644d54bf51c704b445c1

**Version**
0.14.3

**To Reproduce**

**Expected behavior**
Remove instructions, possibly provide some on using the API directly?

**Screenshots**

**Logs**

**Additional context**

**Comment by Freika** [comment]
Yeah, I'm planning to implement import of the `.rec` file instead. Have no idea why they removed the button for downloading json file

**Comment by palitu** [comment]
awesome, i dont use owntracks, but do use the OT recorder (well i did!), so i only have access to the .rec files.  Looking forward to the new import functionality.

I would also love if you could publish a "standard" json or csv type of import, so that I can create one from a custom source.

Thanks!

**Comment by Freika** [comment]
> I would also love if you could publish a "standard" json or csv type of import, so that I can create one from a custom source.

You can find it here: https://github.com/Freika/dawarich/blob/fb2468ab3d83bbef861481bb1ca6b4fbc92b67be/spec/fixtures/files/geojson/export.json?short_path=b86f4b4

Copy-paste it to any JSON beautifier to have a proper look to the file structure. Basically, it's a valid [GeoJSON](https://datatracker.ietf.org/doc/html/rfc7946) file with an important custom `timeline` property. Without it file will not be imported because Dawarich needs both coordinates AND time.

**Comment by Freika** [comment]
Fixed in https://github.com/Freika/dawarich/pull/328, will be available in the next release
