### ISSUE TITLE
Anyway to make Owntrack app always record?

### ISSUE THREAD

**Issue by Danielson89** [Freika/dawarich#341]
Not sure why but Owntrack seems to not bother tracking location.  If you manually send location it works fine,  the settings is set to always allow GPS in the privacy settings,  what I generally need to do is go to Google Timeline and export it daily to get the latest maps which is delaying me from deleting my Google account.   

OS: Ubuntu 22.04
Version: 0.15.3 have pulled latest today to 0.15.4 
All Ubuntu updates are up to date and Trend Micro Deep Security disabled
SSL: Up to date and expiring 5/11/2024

Thanks

**Comment by Freika** [comment]
Please provide more details if it's a Dawarich problem, or, if it's an Owntracks problem, open an issue in Owntracks repo.

**Comment by sunstep** [comment]
Have you set it to move mode?

**Comment by Danielson89** [comment]
> Please provide more details if it's a Dawarich problem, or, if it's an Owntracks problem, open an issue in Owntracks repo.

I'm thinking it's an iOS problem as I've now changed the app OwnTrack from "Move" to "Significant" and it's started recording again.  I'm running iOS 18.1 Beta 7

**Comment by Danielson89** [comment]
> I've now changed the app OwnTrack from "Move" to "Significant" and it's started recording again

 I've now changed the app OwnTrack from "Move" to "Significant" and it's started recording again

**Comment by Freika** [comment]
@Danielson89 for iOS I find Overland more reliable client to track geodata

**Comment by sunstep** [comment]
For me Owntracks is working reliably. Move mode is supposed to be continuously recording your location while significant mode is less accurate because it reports your location less frequently. Now I am not sure how IOS works but it could a be a setting preventing owntracks from properly functioning as it should. Could be maybe related to battery optimization so I would definitely try to see if there is a way to ignore any battery optimization for owntracks

I heard that Overland is more reliable than owntracks and since you are on IOS, you could try to use it and see if that works well for you.
