### ISSUE TITLE
Make telemetry opt-in

### ISSUE THREAD

**Issue by alangrafu** [Freika/dawarich#491]
**Describe the bug**
Opt-out telemetry risks that people send their data without their consent. It is better to have an opt-in approach where only people _really_ willing to share their data can do so.

**Version**
0.19.2

**To Reproduce**
n/a

**Expected behavior**
Dawarich shouldn't send telemetry unless `ENABLE_TELEMETRY` is `true` or some similar, voluntary approach.

**Comment by Freika** [comment]
For now, I'd prefer to leave it as is. The feature was clearly defined in the changelog, and I created a [page](https://dawarich.app/docs/tutorials/telemetry) on the website and updated the [page](https://dawarich.app/docs/environment-variables-and-settings) listing possible env vars to include `DISABLE_TELEMETRY`.

To provide more transparency, with the next release, I'll also create visible notifications in the Dawarich interface (notifications area on the screenshot) for those who might not be reading changelogs.

<img width="519" alt="изображение" src="https://github.com/user-attachments/assets/cf018998-162d-41d7-93ef-0eb561c2433b">

In the release notes to [0.19.2](https://github.com/Freika/dawarich/releases/tag/0.19.2) I provided my reasons for introducing telemetry, the code clearly [states](https://github.com/Freika/dawarich/blob/master/app/services/telemetry/gather.rb#L8-L31) what exactly is being sent (only number of daily active users, app version and instance_id, that is being built by hashing first user's API key) and where to.

In an open-source application, there is no way not to be transparent about what you're doing with user's data, and I can confidently state that I have access to none of it.

**Comment by alangrafu** [comment]
In that case it would make sense to add the variable in the [docker-compose example](https://github.com/Freika/dawarich/blob/master/docker-compose.yml#L125) explicitly, ideally with `true` as a default.

**Comment by suth** [comment]
I don't think the issue is asking why or what you are collecting, but why it should be implemented as an opt-out option, especially for existing installs. According to the changelog this project uses semantic versioning, so I assumed that a patch release would only contain bugfixes. For major or minor releases I'll read the changelog, but I never would have assumed defaulting to privacy was a bug.

**Comment by Freika** [comment]
@suth also according [semantic versioning](https://semver.org/#spec-item-4), 

> 4. Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

**Comment by suth** [comment]
@Freika wasn't aware of that, but you're still avoiding the question of why you chose to make it opt-out. Privacy is important, especially to people who have chosen this as a replacement to less privacy conscious solutions. I don't think you're up to anything nefarious so it seems like something you should reconsider.

**Comment by Freika** [comment]
It would be hard to do anything nefarious with the number of daily users, app version and instance_id in an application that is open-source :) The answer is simple: making this an opt-in feature would mean I will be able to gather a very unreliable amount of information on how many people are actually using Dawarich. I would like to know at least a ballpark number that would make sense, otherwise it would be as useful as the number of GitHub stars or docker downloads. I hope this makes it clear.

**Comment by suth** [comment]
I think @alangrafu's solution would be a fair compromise with a default of true in the compose example. Would opt-in new installs by default, give them a transparent way to disable, and avoid opting in existing installs without their consent.

**Comment by Freika** [comment]
The env var will be added in the next release

**Comment by Freika** [comment]
Env var is introduced in [0.19.4](https://github.com/Freika/dawarich/releases/tag/0.19.4)

**Comment by suth** [comment]
@Freika sorry but this is not what @alangrafu suggested, you're still opting in existing installs without their consent. It's a nuanced issue and while you might say "oh there's nothing sensitive being collected," where you decide to draw the line could change in the future. It might even be good for the health of the project to collect more non-sensitive usage data some day in the future - but if your defense of making it opt-out is that you're only collecting 3 data points, then it would be incredibly dishonest if you ever need to collect more. Instead of painting yourself into a corner, you could make it opt-in and give yourself some moral wiggle room for the future.

On top of that, I assume you're not collecting IP addresses since they were not mentioned, but if your domain ever goes defunct someone else could pick it up and suddenly they could start recording IPs and know exactly what installations are running versions with security vulnerabilities. Obviously there's always a risk of this, but you're choosing what risk to take on behalf of users without their consent.

I know you really want to learn more about the health of your project, but I think you should accept that existing installs have not consented to what you'd like to collect. With something as sensitive as location tracking, it won't be good for the long term health of your project if your attitude isn't 100% on the side of privacy by default.

**Comment by Freika** [comment]
I think I did literally everything to inform all interested parties, including existing users (via in-app notification).

As I already pointed out, opt-in telemetry would be basically useless. If you can suggest any other reliable way to count somewhat real number of users, that would be actually great, but I'm not aware of one.

IP addresses are not being tracked, nothing except already defined data points is being recorded.

I think you're incorrect to assume I'm not taking privacy seriously. If that would be the case, I wouldn't bother writing all those changelogs and release notes, meticulously describing every detail. I am also completely transparent about telemetry.

**Comment by Freika** [comment]
After careful consideration, I decided to change telemetry to be [opt-in by default](https://github.com/Freika/dawarich/releases/tag/0.19.6). Antagonizing with the community is not worth any amount of data of any precision.

@alangrafu @suth thank you for the discussion!

**Comment by suth** [comment]
Thank you! I really appreciate your consideration, this is the way I've seen a lot of self-hosted projects work.

Personally I wouldn't mind if `ENABLE_TELEMETRY` was set to true in the docker-compose example, as with the new approach it means it doesn't affect existing installs. I've seen other projects do this and it seems like a fair compromise that gives you a larger sample size from people who don't have strong feelings about telemetry, but still gives anyone concerned a clear way to disable before install.
