### ISSUE TITLE
How to handle bad Google Takeout data?

### ISSUE THREAD

**Issue by marsmathis** [Freika/dawarich#517]
**Describe the bug**
My Google Takeout data is very bad during October 2020.

    {
      "latitudeE7": 50xxxxxxx,
      "longitudeE7": 8xxxxxxx,
      "accuracy": 20,
      "source": "WIFI",
      "deviceTag": 161xxxxxxx,
      "deviceDesignation": "UNKNOWN",
      "timestamp": "2020-10-07T15:20:56.170Z"
    },
    {
      "latitudeE7": 53xxxxxxx,
      "longitudeE7": 9xxxxxxx,
      "accuracy": 16,
      "source": "WIFI",
      "deviceTag": 201xxxxxxx,
      "timestamp": "2020-10-07T15:24:32.603Z"
    },
    {
      "latitudeE7": 50xxxxxxx,
      "longitudeE7": 8xxxxxxx,
      "accuracy": 20,
      "source": "WIFI",
      "deviceTag": 161xxxxxxx,
      "deviceDesignation": "UNKNOWN",
      "timestamp": "2020-10-07T15:25:57.221Z"
    },
    {
      "latitudeE7": 53xxxxxxx,
      "longitudeE7": 9xxxxxxx,
      "accuracy": 15,
      "source": "WIFI",
      "deviceTag": 201xxxxxxx,
      "timestamp": "2020-10-07T15:29:29.751Z"
    },
    {
      "latitudeE7": 50xxxxxxx,
      "longitudeE7": 8xxxxxxx,
      "accuracy": 20,
      "source": "WIFI",
      "deviceTag": 161xxxxxxx,
      "deviceDesignation": "UNKNOWN",
      "timestamp": "2020-10-07T15:30:53.123Z"
    },

**Version**
0.19.3

**To Reproduce**
not applicable

**Expected behavior**
Bad points are filtered out. I don’t know how I would figure out which of these points are actually correct and which should be discarded. Google does filter them, but it is unclear what they base their filter rules on.

**Screenshots**
![Untitled](https://github.com/user-attachments/assets/602ff532-59c7-4f2a-b1b6-d0da0292acc2)
(blurred for privacy reasons, but you can clearly see that the line always jumps back and forth; the total distance during Oct 2020 alone is pretty much exactly 6 million km)

**Additional context**
I know this is inherently a Google problem and not one of Dawarich, but maybe this can be a pointer towards thinking about a rejection algorithm for bad data points which is built into Dawarich.

**Comment by Freika** [comment]
I can see from the json you have provided that your data was tracked at least on two different devices:

> "deviceTag": 161xxxxxxx,
> "deviceTag": 201xxxxxxx,

This is probably where the problem lies. For now, there is no way in Dawarich to choose data from which device should be rendered, but it will be implemented, hopefully before the end of this year.

**Comment by hopeseekr** [comment]
@marsmathis I had this same problem.

Are you a technical person? 

If you have a certain amount of termerity and grit, you can use ChatGPT or even Bing Copilot (for free) witht this query:

> Please create for me a python program for removing from this JSON file every JSON block that contains "  "deviceTag": 161xxxxxxx". And please show me how to run it. The file name is called "Records.json." Thank you so much!

Then that should create a jSON parser that removes the duplicated devices...

-----

But since it's already in the points data.... You can do this instead....

Load up the PostgreSQL database via the `psql` command, probably inside your docker container:


You should absolutely back up your database or points table before hand...

```
docker compose exec dawarich_db bash
psql dawarich
# Backup the Points table:
CREATE TABLE points_v1 AS SELECT * FROM points;
DELETE FROM points
WHERE raw_data @> '{"deviceTag": "DEVICE_TAG_TO_DELETE"}';

# If evyerhing looks good, delete the backup:
DROP TBLE points_v1;

# If stuff looks bad, restore the data:
begin;
TRUNCATE points;
INSERT INTO points SELECT * FROM points_v1;
commit;
```

This should clear up your database!

**Comment by marsmathis** [comment]
@hopeseekr Okay, I fixed it now based on your comment and the FAQ on the website. What I did:

```
# docker exec -it dawarich_app /bin/sh
# bin/rails console
# points = Point.where("raw_data->>'deviceTag' = ?", '161xxxxxxx').where("timestamp > ?", 1600207200)
# points.destroy_all
```
